language: node_js
sudo: false
node_js:
 - 10
install:
  - npm install lerna -g
script:  
  - lerna bootstrap
jobs:
  include:
    - stage: libzy-lib publish
      node_js: "10"
      before_script: cd packages/libzy-lib
      script: 
        - npm i
        - npm run build            
      deploy:
        provider: npm
        email: "mehmetbaran@mehmetbaran.net"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
      after_deploy: cd ../../
    - stage: libzy publish
      node_js: "10"
      script: echo "Deploying libzy to npm ..."
      before_deploy: cd packages/libzy     
      deploy:
        provider: npm
        email: "mehmetbaran@mehmetbaran.net"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
      after_deploy: cd ../../